name: ci-cd

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t hassanb111/gradlink:${GITHUB_SHA} .
          docker push hassanb111/gradlink:${GITHUB_SHA}

      - name: SSH and deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          script: |
            docker pull hassanb111/gradlink:${GITHUB_SHA}
            docker stop gradlink || true
            docker rm gradlink || true
            docker run -d --name gradlink -p 5000:8080 hassanb111/gradlink:${GITHUB_SHA}
