name: ci

on:
  push:
    branches:
      - master  # Only trigger on pushes to the master branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build -t hassanb111/gradlink:1 .

          # Push the Docker image to Docker Hub
          docker push hassanb111/gradlink:1
